# Generated by Django 4.2.1 on 2024-02-17 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_interview_invitation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Avatar",
        ),
    ]
